version: "3.8"
services:
    api.kafkacourse:
        container_name: api.kafkacourse
        build: .
        environment:
            KAFKACOURSE_DATABASE_HOST: mariadb.kafkacourse
            KAFKACOURSE_KAFKA_URI: kafka.kafkacourse:9091
        ports:
            -   "8080:8080"
        networks:
            - bubble

    mariadb.kafkacourse:
        platform: linux/amd64
        container_name: mariadb.kafkacourse
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: kafkacourse
        command: mysqld --innodb-buffer-pool-size=64M
        ports:
            -   "3305:3306"
        networks:
            - bubble

    zookeeper.kafkacourse:
        container_name: zookeeper.kafkacourse
        image: 'bitnami/zookeeper:3.5.9-debian-10-r13'
        ports:
            -   "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka.kafkacourse:
        container_name: kafka.kafkacourse
        image: 'bitnami/kafka:2.8.1-debian-10-r18'
        ports:
            - '9091:9091'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9091
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper.kafkacourse:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper.kafkacourse

networks:
    bubble:
        external: true