version: "3.8"
services:
    api.kafkacourse:
        container_name: api.kafkacourse
        build: .
        env_file:
            -   .env
        environment:
            KAFKACOURSE_DATABASE_HOST: mariadb.kafkacourse
            KAFKACOURSE_KAFKA_URI: kafka.kafkacourse:9092
        ports:
            -   "8080:8080"
        networks:
            - bubble
        depends_on:
            - mariadb.kafkacourse
            - kafka.kafkacourse

    mariadb.kafkacourse:
        platform: linux/amd64
        container_name: mariadb.kafkacourse
        image: mariadb:latest
        env_file:
            -   .env
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: kafkacourse
        command: mysqld --innodb-buffer-pool-size=64M
        ports:
            -   "3305:3305"
        networks:
            - bubble

    zookeeper.kafkacouse:
        container_name: zookeeper.kafkacourse
        image: 'bitnami/zookeeper:latest'
        ports:
            -   "9092:9092"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka.kafkacourse:
        container_name: kafka.misterbelly
        image: 'bitnami/kafka:2.8.1-debian-10-r18'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper.misterbelly:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper.kafkacourse

networks:
    bublle:
        external: true