spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3305/kafkacourse?createDatabaseIfNotExist=true&serverTimeZone=UTC
        username: root
        password: root
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

twitter:
    consumer:
        key: 0tgQQ2ZgZVAh3L2S7q8HaO7Mf
        secret: xFip1nkqtoOsIUbKdRmXGjfZ4a9N5rFbYJAStfz9gUUwpkhwOw
    token: 1416196031511994368-H7lQF2rpQsJtnq3WAl3PiD7nDgakll
    secret: RfVkVoZ0ZnjtkMQP4xgBSClz5XVicW0JxIHpttUtGgdJy

elastic:
    port: 443
    hostname: kafka-course-705596321.us-east-1.bonsaisearch.net
    username: ial8hxadec
    password: hzyncr12p6

kafka:
    bootstrap-server: localhost:9091
    consumer:
        group-id: kafka-demo-elasticsearch
        auto-offset.reset: earliest
        enable.auto-commit: false
        max.poll.records: 200
    producer:
        enable.idempotence: true
        acks: all
        max.in-flight.requests-per-connection: 5
        compression.type: snappy
        linger.ms: 20
    streams:
        application.id: demo-kafka-streams